#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, "SKILL.md");
const destination = resolve(root, "packages/client/src/skill.generated.ts");

const content = readFileSync(source, "utf8");
const escaped = content
  .replaceAll("\\", "\\\\")
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${");

writeFileSync(
  destination,
  `// AUTO-GENERATED by scripts/embed-skill.ts — do not edit\nexport const SKILL_MD = \`${escaped}\`;\n`,
);

console.log(
  `Embedded ${content.length} bytes from SKILL.md in ${destination}.`,
);
